/* auto-generated by paperforge notation_registry.py — do not edit */
window.paperforgeNotation = {"farDelayMs": 1000, "nearDelayMs": 400};
window.PAPERFORGE_NOTATION = {
 "GQ": {
  "html": "The absolute Galois group \\(\\GQ=\\operatorname{Gal}(\\overline{\\mathbb{Q}}_2/\\mathbb{Q}_2)\\) of the field of \\(2\\)-adic numbers.",
  "href": "paper.html"
 },
 "Qtwo": {
  "html": "\\(\\Qtwo\\): the field of \\(2\\)-adic numbers.",
  "href": null
 },
 "Zhat": {
  "html": "\\(\\Zhat\\): the profinite completion of \\(\\mathbb{Z}\\). Exponentiation by its elements has the usual profinite meaning.",
  "href": null
 },
 "w": {
  "html": "The idempotent \\(\\w\\in\\Zhat\\): equal to \\(1\\) in \\(\\mathbb{Z}_2\\) and \\(0\\) in \\(\\mathbb{Z}_\\ell\\) for every odd prime \\(\\ell\\); thus \\(\\w^2=\\w\\).",
  "href": "paper.html"
 },
 "TA": {
  "html": "The tame group \\(\\TA=\\langle\\sigma,\\tau\\mid\\tau^\\sigma=\\tau^2\\rangle_{\\mathrm{prof}}\\), the common tame quotient of \\(\\GA\\) and \\(\\GQ\\).",
  "href": "paper.html"
 },
 "GA": {
  "html": "\\(\\GA\\): the group presented in the main theorem; formally \\(\\GA=F/N_A\\), the marked quotient of the free profinite group on \\(\\sigma,\\tau,x_0,x_1\\).",
  "href": "paper.html#sec-candidate-the-marked-quotient-construction"
 },
 "WA": {
  "html": "\\(\\WA\\trianglelefteq\\GA\\): the closed normal subgroup generated by \\(x_0,x_1\\); it is pro-\\(2\\).",
  "href": "paper.html#sec-candidate-the-marked-quotient-construction"
 },
 "WF": {
  "html": "\\(\\WF\\): the wild inertia subgroup of \\(\\GQ\\), with \\(\\GQ/\\WF\\cong\\TA\\).",
  "href": "paper.html#prop-tamequotient"
 },
 "Arf": {
  "html": "\\(\\Arf\\): the Arf invariant of a quadratic form over \\(\\F_2\\).",
  "href": null
 },
 "rec": {
  "html": "\\(\\rec\\): the local reciprocity map of local class field theory.",
  "href": null
 },
 "bdry": {
  "html": "The common boundary \\(\\bdry=\\TA\\times_{\\mathbb{Z}_2}\\Pi\\), through which the tame and maximal pro-\\(2\\) quotients are glued.",
  "href": "paper.html"
 },
 "D0": {
  "html": "\\(D_0=\\langle A,S,Y\\mid r_0\\rangle_{\\mathrm{pro}-2}\\): the standard rank-three, \\(q=2\\), dyadic Demushkin group.",
  "href": "paper.html#subsec-standarddyadic"
 },
 "Bab": {
  "html": "\\(B_{\\mathrm{ab}}=D_0^{\\mathrm{ab}}=C_2t\\oplus\\mathbb{Z}_2\\bar S\\oplus\\mathbb{Z}_2\\bar Y\\): the marked abelianization of \\(D_0\\).",
  "href": "paper.html#subsec-standarddyadic"
 },
 "chi0": {
  "html": "The canonical orientation character \\(\\chi_0\\) of \\(D_0\\): \\(\\chi_0(t)=-1\\), \\(\\chi_0(\\bar S)=1\\), \\(\\chi_0(\\bar Y)=\\eta\\).",
  "href": "paper.html#subsec-standarddyadic"
 },
 "nuur": {
  "html": "The unramified coordinate \\(\\nu_{\\mathrm{ur}}\\), normalized geometrically: \\(\\nu_{\\mathrm{ur}}(\\Phi_{\\mathrm{geom}})=1\\) for geometric Frobenius.",
  "href": "paper.html"
 },
 "r0": {
  "html": "The standard relator \\(r_0=A^2S^4[S,Y]\\) of the Demushkin group \\(D_0\\).",
  "href": "paper.html#subsec-standarddyadic"
 },
 "calY": {
  "html": "A boundary-framed marked target \\(\\mathcal Y=(Y,L_Y,\\pi_Y,\\theta_Y)\\): ambient profinite \\(Y\\), finite \\(2\\)-group \\(L_Y\\triangleleft Y\\), tame quotient \\(\\pi_Y:Y\\twoheadrightarrow H\\) with kernel \\(L_Y\\), and \\(\\theta_Y:Y\\to E\\).",
  "href": "paper.html#def-framed"
 },
 "Ytarget": {
  "html": "The ambient profinite group of the boundary-framed marked target \\(\\mathcal Y=(Y,L_Y,\\pi_Y,\\theta_Y)\\).",
  "href": "paper.html#def-framed"
 },
 "Ygen": {
  "html": "The generator \\(Y\\) of the standard Demushkin group \\(D_0=\\langle A,S,Y\\mid r_0\\rangle_{\\mathrm{pro}-2}\\).",
  "href": "paper.html#subsec-standarddyadic"
 },
 "LY": {
  "html": "\\(L_Y\\triangleleft Y\\): the finite \\(2\\)-group kernel of the tame quotient \\(\\pi_Y\\) of the boundary-framed target; the induction is ordered by \\(|L_Y|\\).",
  "href": "paper.html#def-framed"
 },
 "piY": {
  "html": "\\(\\pi_Y:Y\\twoheadrightarrow H\\): the tame-quotient map of the boundary-framed target, with kernel \\(L_Y\\).",
  "href": "paper.html#def-framed"
 },
 "thetaY": {
  "html": "\\(\\theta_Y:Y\\to E\\): the homomorphism to the elementary abelian part of the boundary-framed target.",
  "href": "paper.html#def-framed"
 },
 "qY": {
  "html": "\\(q_Y=(\\pi_Y,\\theta_Y):Y\\to H\\times E\\), the combined framing map of the boundary-framed target.",
  "href": "paper.html#def-framed"
 },
 "Pi": {
  "html": "\\(\\Pi=\\langle\\sigma,x_0,x_1\\mid x_0^{\\sigma^2}x_0[x_1,\\sigma]=1\\rangle_{\\mathrm{pro}\\text{-}2}\\): the maximal pro-\\(2\\) quotient of \\(\\GA\\), abstractly \\(\\cong G_{\\Qtwo}(2)\\).",
  "href": "paper.html#eq-Pi"
 },
 "nu2": {
  "html": "\\(\\nu_2:\\Pi\\twoheadrightarrow\\mathbb{Z}_2\\): the unramified coordinate of the maximal pro-\\(2\\) quotient (the marking of the pair \\((\\Pi,\\nu_2)\\)).",
  "href": "paper.html#eq-nu2"
 },
 "eGamma": {
  "html": "The boundary-framed exact-image count \\(e_\\Gamma^\\beta(\\mathcal Y)=\\#\\{f:\\Gamma\\twoheadrightarrow Y: q_Yf=\\beta b_\\Gamma\\}\\), for \\(\\Gamma\\in\\{\\GA,\\GQ\\}\\).",
  "href": "paper.html#eq-eGamma"
 },
 "bGamma": {
  "html": "The boundary epimorphism \\(b_\\Gamma:\\Gamma\\twoheadrightarrow\\bdry\\) (for \\(\\Gamma\\in\\{\\GA,\\GQ\\}\\)), through which boundary-framed counting is compared.",
  "href": "paper.html"
 },
 "Dloc": {
  "html": "\\(D_{\\mathrm{loc}}=G_{\\Qtwo}(2)\\): the maximal pro-\\(2\\) quotient of the local absolute Galois group, marked by \\(\\nu_{\\mathrm{ur}}\\).",
  "href": "paper.html#prop-markedDem"
 },
 "Htarget": {
  "html": "The finite tame-target group \\(H\\) of the boundary-framed tuple: \\(\\pi_Y:Y\\twoheadrightarrow H\\) with kernel \\(L_Y\\).",
  "href": "paper.html#def-framed"
 },
 "Etarget": {
  "html": "The finite elementary abelian \\(2\\)-group \\(E\\) of the boundary-framed tuple: \\(\\theta_Y:Y\\to E\\).",
  "href": "paper.html#def-framed"
 },
 "tTors": {
  "html": "The order-two torsion generator \\(t\\) of \\(B_{\\mathrm{ab}}=C_2t\\oplus\\mathbb{Z}_2\\bar S\\oplus\\mathbb{Z}_2\\bar Y\\), with \\(\\chi_0(t)=-1\\).",
  "href": "paper.html#subsec-standarddyadic"
 },
 "sigma": {
  "html": "\\(\\sigma\\): the Frobenius-lift generator among the four generators \\(\\sigma,\\tau,x_0,x_1\\) of \\(\\GA\\); tame relation \\(\\tau^\\sigma=\\tau^2\\).",
  "href": "paper.html#thm-main"
 },
 "tau": {
  "html": "\\(\\tau\\): the tame-inertia generator of \\(\\GA\\), with \\(\\tau^\\sigma=\\tau^2\\).",
  "href": "paper.html#thm-main"
 },
 "x0": {
  "html": "\\(x_0\\): one of the two wild generators of \\(\\GA\\); the closed normal subgroup \\(\\WA\\) they generate is required to be pro-\\(2\\).",
  "href": "paper.html#thm-main"
 },
 "x1": {
  "html": "\\(x_1\\): one of the two wild generators of \\(\\GA\\) (see \\(x_0\\)).",
  "href": "paper.html#thm-main"
 },
 "eta": {
  "html": "\\(\\eta=(-3)^{-1}\\in\\mathbb{Z}_2^\\times\\): the orientation unit, a topological generator of \\(1+4\\mathbb{Z}_2\\); \\(\\chi_0(\\bar Y)=\\eta\\).",
  "href": "paper.html#subsec-standarddyadic"
 }
};
/* PreTeXt UI layer.
   (1) A global detail slider that reveals detail tiers by level.
   (2) Notation hovers that reveal a definition without a knowl underline
       (event-delegated, so lazily-typeset math is covered).
   (3) Proof-local "details" button that expands the proof text in place.
   (4) Contents sidebar hidden on page load. */
(function () {
  "use strict";

  // --- Notation registry. Generated per-instance from the document's
  //     <notation> list (single source of truth). Entry formats:
  //       key: "definition html"                          (no context link)
  //       key: {html: "...", href: "sec-x.html#def-id"}   (with context link)
  var NOTATION = window.PAPERFORGE_NOTATION || {};

  // Hover delays (ms). A far-marked symbol (.ptxfar wrapper, see
  // ingest/notation_far.py) waits FAR_DELAY before showing its definition;
  // near symbols show promptly. Override via window.paperforgeNotation.
  var CFG = window.paperforgeNotation || {};
  var FAR_DELAY_MS = CFG.farDelayMs != null ? CFG.farDelayMs : 1000;
  var NEAR_DELAY_MS = CFG.nearDelayMs != null ? CFG.nearDelayMs : 150;

  function ready(fn) {
    if (document.readyState !== "loading") fn();
    else document.addEventListener("DOMContentLoaded", fn);
  }

  function levelOf(el) {
    var m = /\bdetail-level-(\d+)\b/.exec(el.className);
    return m ? +m[1] : 0;
  }

  // Reveal machinery: tier elements are either born-hidden <details> knowls
  // (opened directly) or inline blocks like <p detail-level="2"> (revealed by
  // a `show-dl-N` class on a container — body for the global slider, the
  // proof element for the local button; CSS does the rest).
  function setTierClasses(container, level) {
    for (var l = 2; l <= 9; l++) {
      container.classList.toggle("show-dl-" + l, l <= level);
    }
  }

  function buildSlider() {
    var items = Array.prototype.slice.call(
      document.querySelectorAll('[class*="detail-level-"]'));
    if (!items.length) return;
    var max = items.reduce(function (a, d) { return Math.max(a, levelOf(d)); }, 1);

    var wrap = document.createElement("div");
    wrap.className = "detail-slider";
    wrap.innerHTML =
      '<label for="detail-range">Detail</label>' +
      '<input id="detail-range" type="range" min="0" max="' + max + '" value="0" step="1">' +
      '<span class="detail-val">0/' + max + '</span>';

    var host = document.querySelector("#ptx-masthead") || document.body;
    host.appendChild(wrap);

    var range = wrap.querySelector("input");
    var out = wrap.querySelector(".detail-val");
    function apply() {
      var t = +range.value;
      out.textContent = t + "/" + max;
      items.forEach(function (d) {
        if (d.tagName === "DETAILS") d.open = levelOf(d) <= t;
      });
      setTierClasses(document.body, t);
    }
    range.addEventListener("input", apply);
    apply();
  }

  // Proof-local details: a small button on the "Proof" line (visible only
  // while the proof is open) steps the proof's own tiers up and back down —
  // the proof text expands in place.
  function wireProofDetails() {
    var proofs = Array.prototype.slice.call(
      document.querySelectorAll("details.hiddenproof"));
    proofs.forEach(function (proof) {
      var tiers = Array.prototype.slice.call(
        proof.querySelectorAll('[class*="detail-level-"]'));
      if (!tiers.length) return;
      var levels = [];
      tiers.forEach(function (d) {
        var l = levelOf(d);
        if (levels.indexOf(l) < 0) levels.push(l);
      });
      levels.sort(function (a, b) { return a - b; });
      var summary = proof.querySelector("summary");
      if (!summary) return;
      var btn = document.createElement("button");
      btn.className = "detail-next-btn";
      summary.appendChild(btn);
      var cur = 0;
      function nextLevel() {
        for (var i = 0; i < levels.length; i++)
          if (levels[i] > cur) return levels[i];
        return null;
      }
      function label() {
        btn.textContent = nextLevel() ? "▸ details" : "▾ less";
      }
      btn.addEventListener("click", function (e) {
        e.preventDefault();      // do not toggle the enclosing summary
        e.stopPropagation();
        var nxt = nextLevel();
        cur = nxt !== null ? nxt : 0;
        setTierClasses(proof, cur);
        tiers.forEach(function (d) {
          if (d.tagName === "DETAILS") d.open = levelOf(d) <= cur;
        });
        label();
      });
      label();
    });
  }

  // Contents hidden on page load (the theme's toggle still works).
  function hideTocOnLoad() {
    var sb = document.getElementById("ptx-sidebar");
    if (!sb) return;
    sb.classList.add("hidden");
    sb.classList.remove("visible");
    var btn = document.getElementById("ptx-toc-toggle");
    if (btn) btn.setAttribute("aria-expanded", "false");
  }

  // Notation hovers, event-delegated: works regardless of when MathJax
  // typesets a given expression (required for lazy typesetting, where math
  // renders as it scrolls into view).
  function wireNotation() {
    var pop = document.createElement("div");
    pop.className = "notation-popup";
    document.body.appendChild(pop);
    var hideTimer, showTimer, hoverEl = null;

    pop.addEventListener("mouseenter", function () { clearTimeout(hideTimer); });
    pop.addEventListener("mouseleave", scheduleHide);

    function keyOf(el) {
      var m = /\bptxnotn-([A-Za-z0-9]+)\b/.exec(el.className);
      return m ? m[1] : null;
    }
    function entryFor(k) {
      var v = NOTATION[k];
      if (!v) return null;
      return typeof v === "string" ? { html: v, href: null } : v;
    }
    function isFar(el) {
      return !!(el.closest && el.closest(".ptxfar"));
    }
    function show(el) {
      var k = keyOf(el);
      var entry = k && entryFor(k);
      if (!entry) return;
      clearTimeout(hideTimer);
      var html = '<span class="notation-popup-key">' + k + '</span>' + entry.html;
      if (entry.href) {
        html += '<a class="notation-ctx-link" href="' + entry.href +
                '">see definition in context &#x2197;</a>';
      }
      pop.innerHTML = html;
      var r = el.getBoundingClientRect();
      // Place BELOW the symbol so the popup never covers the text being read.
      pop.style.top = (window.scrollY + r.bottom + 6) + "px";
      pop.style.left = (window.scrollX + r.left) + "px";
      pop.classList.add("show");
      if (window.MathJax && MathJax.typesetPromise) {
        MathJax.typesetPromise([pop]).catch(function () {});
      }
    }
    function scheduleHide() {
      clearTimeout(showTimer);
      hideTimer = setTimeout(function () { pop.classList.remove("show"); }, 180);
    }

    document.addEventListener("mouseover", function (e) {
      var el = e.target.closest
        ? e.target.closest('[class*="ptxnotn-"]') : null;
      if (el === hoverEl) return;
      if (el) {
        hoverEl = el;
        clearTimeout(hideTimer);
        clearTimeout(showTimer);
        var delay = isFar(el) ? FAR_DELAY_MS : NEAR_DELAY_MS;
        showTimer = setTimeout(function () { show(el); }, delay);
      } else if (hoverEl && !(e.target.closest &&
                              e.target.closest(".notation-popup"))) {
        hoverEl = null;
        scheduleHide();
      }
    });
  }

  ready(function () {
    hideTocOnLoad();
    buildSlider();
    wireProofDetails();
    wireNotation();
  });
})();
